//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AgreeDisagreeReply.java
//  @ Date : 2017-07-06
//  @ Author : 
//
//



package kr.co.unibate.bean;

import java.util.Date;


public class AgreeDisagreeReply {
	public int getAd_reply_num() {
		return ad_reply_num;
	}
	public void setAd_reply_num(int ad_reply_num) {
		this.ad_reply_num = ad_reply_num;
	}
	public int getAd_board_num() {
		return ad_board_num;
	}
	public void setAd_board_num(int ad_board_num) {
		this.ad_board_num = ad_board_num;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getAd_reply() {
		return ad_reply;
	}
	public void setAd_reply(String ad_reply) {
		this.ad_reply = ad_reply;
	}
	public Date getAd_r_date() {
		return ad_r_date;
	}
	public void setAd_r_date(Date ad_r_date) {
		this.ad_r_date = ad_r_date;
	}
	public int getAd_like() {
		return ad_like;
	}
	public void setAd_like(int ad_like) {
		this.ad_like = ad_like;
	}
	public int getAd_dislike() {
		return ad_dislike;
	}
	public void setAd_dislike(int ad_dislike) {
		this.ad_dislike = ad_dislike;
	}
	private int ad_reply_num;
	private int ad_board_num;
	private String id;
	private String ad_reply;
	private Date ad_r_date;
	private int ad_like;
	private int ad_dislike;
	private int board_group_num;
	public int getBoard_group_num() {
		return board_group_num;
	}
	public void setBoard_group_num(int board_group_num) {
		this.board_group_num = board_group_num;
	}
	public String getReply_date() {
		return reply_date;
	}
	public void setReply_date(String reply_date) {
		this.reply_date = reply_date;
	}
	private String reply_date;

}
