//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AgreeDisagreeBoard.java
//  @ Date : 2017-07-06
//  @ Author : 
//
//

package kr.co.unibate.bean;

import java.util.Date;

public class AgreeDisagreeBoard {
	private int board_group_num;

	public int getBoard_group_num() {
		return board_group_num;
	}

	public void setBoard_group_num(int board_group_num) {
		this.board_group_num = board_group_num;
	}

	private int ad_board_num;
	private String ad_subject;
	private String board_content;

	public String getBoard_content() {
		return board_content;
	}

	public void setBoard_content(String board_content) {
		this.board_content = board_content;
	}

	private String board_img;

	public String getBoard_img() {
		return board_img;
	}

	public void setBoard_img(String board_img) {
		this.board_img = board_img;
	}

	public int getAd_board_num() {
		return ad_board_num;
	}

	public void setAd_board_num(int ad_board_num) {
		this.ad_board_num = ad_board_num;
	}

	public String getAd_subject() {
		return ad_subject;
	}

	public void setAd_subject(String ad_subject) {
		this.ad_subject = ad_subject;
	}

	public String getAd_img() {
		return ad_img;
	}

	public void setAd_img(String ad_img) {
		this.ad_img = ad_img;
	}

	public int getBoard_count() {
		return board_count;
	}

	public void setBoard_count(int board_count) {
		this.board_count = board_count;
	}

	public Date getBoard_date() {
		return board_date;
	}

	public void setBoard_date(Date board_date) {
		this.board_date = board_date;
	}

	private int array_num;

	public int getArray_num() {
		return array_num;
	}

	public void setArray_num(int array_num) {
		this.array_num = array_num;
	}

	private String ad_img;
	private int board_count;
	private Date board_date;
}
