//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RTDebate.java
//  @ Date : 2017-07-06
//  @ Author : 
//
//


package kr.co.unibate.bean;

import java.sql.Timestamp;
import java.util.Date;


public class RTDebate {
	private int d_num;
	private String d_subject;
	private Timestamp d_date;
	private String d_content;
	public String getD_content() {
		return d_content;
	}
	public void setD_content(String d_content) {
		this.d_content = d_content;
	}
	public int getD_num() {
		return d_num;
	}
	public void setD_num(int d_num) {
		this.d_num = d_num;
	}
	public String getD_subject() {
		return d_subject;
	}
	public void setD_subject(String d_subject) {
		this.d_subject = d_subject;
	}
	public Timestamp	 getD_date() {
		return d_date;
	}
	public void setD_date(Timestamp d_date) {
		this.d_date = d_date;
	}
}
