//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RTDebate.java
//  @ Date : 2017-07-06
//  @ Author : 
//
//


package kr.co.unibate.bean;

import java.sql.Timestamp;
import java.util.Date;


public class RTResult {
	
	private int d_num;
	private String d_subject;
	private String best_mem;
	private int agree_score;
	private int disagree_score;
	private Timestamp start_date;
	private Timestamp end_date;
	public int getD_num() {
		return d_num;
	}
	public void setD_num(int d_num) {
		this.d_num = d_num;
	}
	public String getD_subject() {
		return d_subject;
	}
	public void setD_subject(String d_subject) {
		this.d_subject = d_subject;
	}
	public String getBest_mem() {
		return best_mem;
	}
	public void setBest_mem(String best_mem) {
		this.best_mem = best_mem;
	}
	public int getAgree_score() {
		return agree_score;
	}
	public void setAgree_score(int agree_score) {
		this.agree_score = agree_score;
	}
	public int getDisagree_score() {
		return disagree_score;
	}
	public void setDisagree_score(int disagree_score) {
		this.disagree_score = disagree_score;
	}
	public Timestamp getStart_date() {
		return start_date;
	}
	public void setStart_date(Timestamp start_date) {
		this.start_date = start_date;
	}
	public Timestamp getEnd_date() {
		return end_date;
	}
	public void setEnd_date(Timestamp end_date) {
		this.end_date = end_date;
	}
	
}
